# Generated by Django 3.2.5 on 2021-08-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210820_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='initial_bid',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
